/**
 * 首页「灵感灯箱」六个 demo 的共享数据 + 类别词汇表。
 *
 * 每个 demo 都是一份「从无锡出发、点进即见、可直接照着走」的完整行程：
 *   · 地点/车次/航班/票价均为手工核对的真实数据；坐标为真实 WGS-84。
 *   · 国内行程（苏州/稻城亚丁）上高德底图，坐标经 lib/gcj02 加偏（tiles:"amap"）。
 *   · 出境行程（京都/冰岛/圣托里尼/摩洛哥）上 OSM 底图，用原始 WGS-84（tiles:"osm"）。
 *
 * 被 /demo/[slug]（完整演示页）、首页展示带（ShowcaseTrip 默认取 suzhou）、
 * 两套地图组件、以及 /api/trips/demo（一键存为可编辑行程）共用——改数据一处生效。
 */

export type Kind = "activity" | "food" | "rest" | "transit";

/** 类别 → 中文短标（列表分类小徽标 / 地图名称标签副题） */
export const KIND_LABEL: Record<Kind, string> = {
  activity: "景点",
  food: "美食",
  rest: "住宿",
  transit: "交通",
};

/** 类别 → 类别色（与 globals.css --c-* 对齐；针脚 / 徽标 / 列表节点共用） */
export const KIND_COLOR: Record<Kind, string> = {
  activity: "var(--c-activity)",
  food: "var(--c-food)",
  rest: "var(--c-rest)",
  transit: "var(--c-transit)",
};

/** 类别色的落地十六进制（地图上需要真实色值，如 marker 描边 / 阴影） */
export const KIND_HEX: Record<Kind, string> = {
  activity: "#6366f1",
  food: "#f97316",
  rest: "#10b981",
  transit: "#3b82f6",
};

/** 地图针脚内嵌的类别图标（lucide 路径，白色描边）。 */
export const KIND_SVG: Record<Kind, string> = {
  activity:
    '<path d="M10 18v-7"/><path d="M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A.5.5 0 0 1 20.5 7h-17a.5.5 0 0 1-.22-.949z"/><path d="M14 18v-7"/><path d="M18 18v-7"/><path d="M3 22h18"/><path d="M6 18v-7"/>',
  food:
    '<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"/>',
  rest:
    '<path d="M2 20v-8a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v8"/><path d="M4 10V6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v4"/><path d="M12 4v6"/><path d="M2 18h20"/>',
  transit:
    '<path d="M8 3.1V7a4 4 0 0 0 8 0V3.1"/><path d="m9 15-1-1"/><path d="m15 15 1-1"/><path d="M9 19c-2.8 0-5-2.2-5-5v-4a8 8 0 0 1 16 0v4c0 2.8-2.2 5-5 5Z"/><path d="m8 19-2 3"/><path d="m16 19 2 3"/>',
};

export const iconSvg = (kind: Kind) =>
  `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round">${KIND_SVG[kind]}</svg>`;

export interface Stop {
  time: string;
  title: string;
  /** 地图名称标签用的短名（去掉括号/说明，避免标签过长） */
  short: string;
  kind: Kind;
  detail: string;
  /** 显示用花费（"¥80" / "¥688/晚" / null=免费不显示） */
  cost: string | null;
  lat: number;
  lon: number;
  /** 该条目的选择依据（行程页可解释性；存为行程时写入 item.why） */
  why?: string;
  /** transit 条目以登机牌 / 车票票根呈现 */
  ticket?: {
    line: string;
    no: string;
    from: string;
    to: string;
    dep: string;
    arr: string;
    dur: string;
    seat: string;
    /** 交通方式：火车（默认）或航班 */
    mode?: "train" | "flight";
    /** 中转说明（如「经上海浦东」「赫尔辛基转机」） */
    via?: string;
  };
}

export interface ShowDay {
  day: number;
  date: string;
  dow: string;
  theme: string;
  tab: string;
  summary: string;
  stops: Stop[];
}

/** 一个完整 demo：卡片信息 + 逐日行程 + 关键信息 + 存库所需元数据 */
export interface DemoTrip {
  slug: string;
  name: string;
  en: string;
  /** 目的地所属地区，如「中国·江苏」「日本·关西」 */
  region: string;
  tagline: string;
  origin: string;
  transport: "train" | "flight";
  /** 交通一句话，如「高铁 20 分直达」「上海转机·关西空港」 */
  transportNote: string;
  /** 卡片/头部日期区间展示，如「07.10 – 07.12」 */
  dateLabel: string;
  /** 时长短语，如「江南三日」「关西红叶四日」 */
  durationLabel: string;
  partySize: number;
  /** 人均预算展示，如「¥1,200 / 人」 */
  budgetLabel: string;
  /** 存库时写入 trip 的总预算（约人均×人数） */
  budgetValue: number;
  /** 存库时写入 travel_style */
  style: string;
  /** 概览段落（demo 页 + 存库 overview） */
  overview: string;
  /** 成稿标题，如「无锡 → 苏州 · 江南三日」 */
  itineraryTitle: string;
  tiles: "amap" | "osm";
  featured?: boolean;
  /** 4–5 条亮点短语，卡片/头部 chips 用 */
  highlights: string[];
  references: { label: string; value: string }[];
  days: ShowDay[];
}

// ─────────────────────────────────────────────────────────────────────────────
// 1) 苏州 · 江南三日（高铁 20 分直达，国内·高德底图）
// ─────────────────────────────────────────────────────────────────────────────
const SUZHOU: DemoTrip = {
  slug: "suzhou",
  name: "苏州",
  en: "SUZHOU",
  region: "中国 · 江苏",
  tagline: "看园林，逛水乡老街",
  origin: "无锡",
  transport: "train",
  transportNote: "沪宁城际 20 分直达",
  dateLabel: "07.10 – 07.12",
  durationLabel: "江南三日",
  partySize: 2,
  budgetLabel: "¥1,200 / 人",
  budgetValue: 3000,
  style: "江南水乡 · 园林与美食 · 节奏轻松",
  itineraryTitle: "无锡 → 苏州 · 江南三日",
  overview:
    "一趟可以直接出发的江南小旅行：第一天入古城看园林、夜游平江路；第二天从虎丘沿七里山塘进城，晚上在网师园听昆曲；第三天切换到金鸡湖的现代苏州，带上伴手礼晚饭前到家。车次、门票、老字号均为真实数据。",
  tiles: "amap",
  featured: true,
  highlights: ["沪宁城际 20 分直达", "拙政园 + 苏博", "平江路夜游", "网师园昆曲"],
  references: [
    { label: "去程", value: "沪宁城际 G7215 无锡 09:04 → 苏州 09:24 · 二等座 ¥19.5" },
    { label: "返程", value: "沪宁城际 G7042 苏州 17:23 → 无锡 17:42 · 二等座 ¥19.5" },
    { label: "住宿", value: "书香府邸·平江府 · 两晚约 ¥1376 · 平江路历史街区内" },
    { label: "预约提醒", value: "拙政园、苏州博物馆均需提前实名预约；网师园夜花园 19:30 开演" },
  ],
  days: [
    {
      day: 1,
      date: "07.10",
      dow: "周五",
      theme: "入城 · 拙政园与平江夜色",
      tab: "园林平江",
      summary: "今日约 ¥888 · 含首晚住宿",
      stops: [
        {
          time: "09:04",
          title: "沪宁城际 G7215 · 无锡 → 苏州",
          short: "苏州站",
          kind: "transit",
          detail: "",
          cost: "¥19.5",
          lat: 31.331,
          lon: 120.612,
          why: "早班城际 20 分钟直达，到站即在古城北缘，寄存行李后全天不赶",
          ticket: {
            line: "沪宁城际",
            no: "G7215",
            from: "无锡",
            to: "苏州",
            dep: "09:04",
            arr: "09:24",
            dur: "20 分",
            seat: "二等座",
            mode: "train",
          },
        },
        {
          time: "10:00",
          title: "书香府邸 · 平江府",
          short: "书香府邸",
          kind: "rest",
          detail: "先寄存行李，出门就是平江路",
          cost: "¥688/晚",
          lat: 31.3182,
          lon: 120.6338,
          why: "住进街区里，去拙政园/苏博步行可达，夜游零通勤",
        },
        {
          time: "10:40",
          title: "拙政园",
          short: "拙政园",
          kind: "activity",
          detail: "中国四大名园之首，宜提前一日预约",
          cost: "¥80",
          lat: 31.3236,
          lon: 120.629,
          why: "苏州园林的巅峰之作，上午人少光线好，留足两小时",
        },
        {
          time: "12:30",
          title: "裕兴记面馆（西北街）",
          short: "裕兴记面馆",
          kind: "food",
          detail: "两面黄脆底浇头，苏式面点老字号",
          cost: "¥45",
          lat: 31.3249,
          lon: 120.622,
          why: "就在拙政园与苏博之间，不为吃饭绕路",
        },
        {
          time: "14:00",
          title: "苏州博物馆",
          short: "苏州博物馆",
          kind: "activity",
          detail: "贝聿铭封山之作，片石假山如水墨",
          cost: "免费预约",
          lat: 31.3228,
          lon: 120.6262,
          why: "建筑本身即展品，与拙政园一墙之隔，顺路即达",
        },
        {
          time: "18:30",
          title: "平江路 · 摇橹船夜游",
          short: "平江路",
          kind: "activity",
          detail: "小桥流水枕河人家，船娘唱一段评弹",
          cost: "¥55",
          lat: 31.3152,
          lon: 120.6336,
          why: "夜色里的水巷是苏州的另一面，回酒店步行五分钟",
        },
      ],
    },
    {
      day: 2,
      date: "07.11",
      dow: "周六",
      theme: "虎丘塔影 · 七里山塘",
      tab: "虎丘山塘",
      summary: "今日约 ¥260",
      stops: [
        {
          time: "09:00",
          title: "虎丘",
          short: "虎丘",
          kind: "activity",
          detail: "吴中第一名胜，千年斜塔与剑池",
          cost: "¥70",
          lat: 31.3402,
          lon: 120.5766,
          why: "苏东坡说「到苏州不游虎丘乃憾事也」，早去避开旅行团",
        },
        {
          time: "11:00",
          title: "七里山塘 · 山塘街",
          short: "七里山塘",
          kind: "activity",
          detail: "古运河畔水上人家，可乘手摇船",
          cost: null,
          lat: 31.3196,
          lon: 120.607,
          why: "从虎丘沿山塘河一路进城，动线顺、免门票",
        },
        {
          time: "12:00",
          title: "荣阳楼（山塘街）",
          short: "荣阳楼",
          kind: "food",
          detail: "百年老店，生煎馒头配卤汁豆腐干",
          cost: "¥35",
          lat: 31.3232,
          lon: 120.6012,
          why: "本地人排队的老字号，就在山塘街上",
        },
        {
          time: "14:00",
          title: "留园",
          short: "留园",
          kind: "activity",
          detail: "与拙政园齐名，移步换景的范本",
          cost: "¥55",
          lat: 31.3226,
          lon: 120.5949,
          why: "比拙政园安静，冠云峰与鸳鸯厅值得慢看",
        },
        {
          time: "19:30",
          title: "网师园 · 夜花园",
          short: "网师园",
          kind: "activity",
          detail: "昆曲评弹实景演出，夜苏州的精华",
          cost: "¥100",
          lat: 31.302,
          lon: 120.6321,
          why: "在真园林里听一折昆曲，体验独此一家",
        },
      ],
    },
    {
      day: 3,
      date: "07.12",
      dow: "周日",
      theme: "金鸡湖畔 · 满载而归",
      tab: "金鸡湖返程",
      summary: "今日约 ¥128 · 含返程车票",
      stops: [
        {
          time: "08:30",
          title: "同得兴精品面馆（十全街）",
          short: "同得兴面馆",
          kind: "food",
          detail: "一碗枫镇大肉面，苏式头汤面的讲究",
          cost: "¥28",
          lat: 31.3035,
          lon: 120.6288,
          why: "苏州人的早晨从头汤面开始，赶早去汤最清",
        },
        {
          time: "10:30",
          title: "诚品书店（金鸡湖）",
          short: "诚品书店",
          kind: "activity",
          detail: "大陆首家诚品，湖畔消磨一上午",
          cost: null,
          lat: 31.3218,
          lon: 120.6923,
          why: "从古城切换到湖畔的现代苏州，雨天备选也稳妥",
        },
        {
          time: "13:30",
          title: "金鸡湖湖滨步道 · 东方之门",
          short: "东方之门",
          kind: "activity",
          detail: "环湖天际线，苏州的现代面孔",
          cost: null,
          lat: 31.3125,
          lon: 120.676,
          why: "饭后沿湖散步消食，摩天轮与音乐喷泉都在这一段",
        },
        {
          time: "15:30",
          title: "采芝斋（观前街总店）",
          short: "采芝斋",
          kind: "food",
          detail: "一百五十年苏式糖果铺，捎份伴手礼",
          cost: "¥80",
          lat: 31.3128,
          lon: 120.6238,
          why: "松子糖 / 苏式话梅，带得走的苏州味",
        },
        {
          time: "17:23",
          title: "沪宁城际 G7042 · 苏州 → 无锡",
          short: "苏州站",
          kind: "transit",
          detail: "",
          cost: "¥19.5",
          lat: 31.331,
          lon: 120.612,
          why: "晚高峰前返程，到无锡赶得上晚饭",
          ticket: {
            line: "沪宁城际",
            no: "G7042",
            from: "苏州",
            to: "无锡",
            dep: "17:23",
            arr: "17:42",
            dur: "19 分",
            seat: "二等座",
            mode: "train",
          },
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// 2) 京都 · 关西红叶四日（上海浦东转机·关西空港，出境·OSM 底图）
// ─────────────────────────────────────────────────────────────────────────────
const KYOTO: DemoTrip = {
  slug: "kyoto",
  name: "京都",
  en: "KYOTO",
  region: "日本 · 关西",
  tagline: "古寺、红叶和千本鸟居",
  origin: "无锡",
  transport: "flight",
  transportNote: "上海浦东 ✈ 关西空港",
  dateLabel: "11.20 – 11.23",
  durationLabel: "关西红叶四日",
  partySize: 2,
  budgetLabel: "¥6,800 / 人",
  budgetValue: 13600,
  style: "古都文化 · 红叶季 · 寺社与和食，节奏舒缓",
  itineraryTitle: "无锡 → 京都 · 关西红叶四日",
  overview:
    "无锡先到上海浦东，直飞关西空港，HARUKA 特急 75 分进京都。四天走遍东山（清水寺·祇園）、岚山（渡月桥·竹林）、金阁寺与伏见稻荷千本鸟居，末日到宇治看平等院、喝中村藤吉抹茶，赶下午航班回程。红叶季 11 月中下旬正当时。",
  tiles: "osm",
  highlights: ["浦东直飞关西 2h15", "清水寺 + 祇園", "岚山竹林 + 金阁寺", "伏见稻荷千本鸟居"],
  references: [
    { label: "去程", value: "MU516 上海浦东 09:15 → 关西空港 12:30 · 经济舱 约¥2,400" },
    { label: "返程", value: "MU515 关西空港 16:40 → 上海浦东 18:20 · 经济舱 约¥2,400" },
    { label: "市内交通", value: "关西空港 HARUKA 特急 75 分到京都；市内建议巴士一日券 ¥50" },
    { label: "住宿", value: "四条河原町 UNIZO 酒店 · 三晚约 ¥1,700 · 地铁/巴士枢纽" },
  ],
  days: [
    {
      day: 1,
      date: "11.20",
      dow: "周四",
      theme: "抵达关西 · 初见京都",
      tab: "落地锦市场",
      summary: "今日约 ¥3,300 · 含机票与首晚",
      stops: [
        {
          time: "09:15",
          title: "MU516 · 上海浦东 → 关西空港",
          short: "关西→京都",
          kind: "transit",
          detail: "",
          cost: "¥2,400",
          lat: 34.9858,
          lon: 135.7588,
          why: "无锡地面 1.5h 到浦东，直飞关西约 2h15，落地换 HARUKA 特急直插京都",
          ticket: {
            line: "东航",
            no: "MU516",
            from: "上海浦东",
            to: "关西空港",
            dep: "09:15",
            arr: "12:30",
            dur: "2h15",
            seat: "经济舱",
            mode: "flight",
            via: "落地转 HARUKA 特急 75 分到京都",
          },
        },
        {
          time: "14:00",
          title: "京都塔展望台",
          short: "京都塔",
          kind: "activity",
          detail: "京都站正对面，先俯瞰整座棋盘古城",
          cost: "¥50",
          lat: 34.9876,
          lon: 135.759,
          why: "出站即到，登高建立方位感，也顺手寄存大件行李",
        },
        {
          time: "15:30",
          title: "UNIZO 酒店（四条河原町）",
          short: "四条酒店",
          kind: "rest",
          detail: "地铁与巴士枢纽，去哪都方便",
          cost: "¥560/晚",
          lat: 35.0037,
          lon: 135.7681,
          why: "住在最热闹的四条，晚间步行可达先斗町与鸭川",
        },
        {
          time: "16:30",
          title: "锦市场",
          short: "锦市场",
          kind: "food",
          detail: "四百年「京都厨房」，边走边吃",
          cost: "¥90",
          lat: 35.005,
          lon: 135.7649,
          why: "玉子烧、豆乳甜甜圈、渍物，一条街尝遍京料理食材",
        },
        {
          time: "18:30",
          title: "先斗町 · 祇園白川夜色",
          short: "先斗町",
          kind: "activity",
          detail: "鸭川畔石板窄巷，红灯笼与料亭",
          cost: null,
          lat: 35.006,
          lon: 135.772,
          why: "第一晚不赶行程，沿鸭川散步感受京都的夜",
        },
      ],
    },
    {
      day: 2,
      date: "11.21",
      dow: "周五",
      theme: "东山古韵 · 清水寺与祇園",
      tab: "东山红叶",
      summary: "今日约 ¥160",
      stops: [
        {
          time: "08:30",
          title: "清水寺",
          short: "清水寺",
          kind: "activity",
          detail: "悬空舞台俯瞰红叶谷，世界遗产",
          cost: "¥20",
          lat: 34.9948,
          lon: 135.785,
          why: "红叶季必到，开门即入避开人潮，清水舞台是京都名片",
        },
        {
          time: "10:30",
          title: "二年坂 · 三年坂",
          short: "二三年坂",
          kind: "activity",
          detail: "通往清水寺的石阶老街，町屋林立",
          cost: null,
          lat: 34.9967,
          lon: 135.7803,
          why: "抹茶冰淇淋与手工店，最有味道的一段坡道",
        },
        {
          time: "12:00",
          title: "顺正 · 汤豆腐",
          short: "顺正汤豆腐",
          kind: "food",
          detail: "南禅寺畔的京都名物汤豆腐",
          cost: "¥120",
          lat: 34.9962,
          lon: 135.782,
          why: "寺院素斋演化的清淡料理，配庭园很京都",
        },
        {
          time: "14:00",
          title: "八坂神社 · 圆山公园",
          short: "八坂神社",
          kind: "activity",
          detail: "祇園的守护社，秋色圆山公园",
          cost: null,
          lat: 35.0036,
          lon: 135.7785,
          why: "从东山一路下坡到祇園，顺势不折返",
        },
        {
          time: "16:00",
          title: "祇園 · 花見小路",
          short: "花見小路",
          kind: "activity",
          detail: "京都艺伎町，黄昏偶遇舞妓",
          cost: null,
          lat: 35.0037,
          lon: 135.7756,
          why: "傍晚的花見小路灯影最美，注意勿追拍舞妓",
        },
      ],
    },
    {
      day: 3,
      date: "11.22",
      dow: "周六",
      theme: "岚山竹林 · 金阁寺",
      tab: "岚山金阁",
      summary: "今日约 ¥130",
      stops: [
        {
          time: "08:30",
          title: "渡月桥 · 岚山",
          short: "渡月桥",
          kind: "activity",
          detail: "桂川上的名桥，背靠红叶岚山",
          cost: null,
          lat: 35.013,
          lon: 135.6779,
          why: "早到人少，桥与山的经典构图光线最好",
        },
        {
          time: "09:10",
          title: "竹林小径 · 天龙寺",
          short: "竹林小径",
          kind: "activity",
          detail: "参天竹道 + 曹源池庭园红叶",
          cost: "¥25",
          lat: 35.016,
          lon: 135.6738,
          why: "竹林清晨最静谧，天龙寺庭园是世界遗产",
        },
        {
          time: "11:00",
          title: "% Arabica 岚山",
          short: "%Arabica",
          kind: "food",
          detail: "桂川畔的网红咖啡，江景拿铁",
          cost: "¥40",
          lat: 35.0102,
          lon: 135.677,
          why: "逛完竹林在河边歇脚，一杯拿铁配岚山",
        },
        {
          time: "14:00",
          title: "金阁寺",
          short: "金阁寺",
          kind: "activity",
          detail: "金箔舍利殿倒映镜湖池",
          cost: "¥25",
          lat: 35.0394,
          lon: 135.7292,
          why: "午后阳光下金阁最耀眼，京都最出片的一景",
        },
        {
          time: "16:00",
          title: "龙安寺 · 石庭",
          short: "龙安寺",
          kind: "activity",
          detail: "十五枯石的枯山水，禅意极简",
          cost: "¥25",
          lat: 35.0344,
          lon: 135.7183,
          why: "与金阁寺同线，坐在檐廊看一会儿枯山水",
        },
      ],
    },
    {
      day: 4,
      date: "11.23",
      dow: "周日",
      theme: "千本鸟居 · 宇治抹茶 · 返程",
      tab: "伏见宇治",
      summary: "今日约 ¥2,520 · 含返程机票",
      stops: [
        {
          time: "08:00",
          title: "伏见稻荷大社",
          short: "伏见稻荷",
          kind: "activity",
          detail: "千本鸟居红色隧道，全天免费开放",
          cost: null,
          lat: 34.9671,
          lon: 135.7727,
          why: "越早人越少，红色鸟居隧道无遮挡才好拍",
        },
        {
          time: "10:30",
          title: "宇治 · 平等院",
          short: "平等院",
          kind: "activity",
          detail: "十円硬币上的凤凰堂，池中倒影",
          cost: "¥30",
          lat: 34.8893,
          lon: 135.8077,
          why: "从伏见南下宇治顺路，凤凰堂是平安时代唯一遗构",
        },
        {
          time: "12:00",
          title: "中村藤吉 · 宇治本店",
          short: "中村藤吉",
          kind: "food",
          detail: "百年茶铺，抹茶荞面与生茶果冻",
          cost: "¥90",
          lat: 34.8912,
          lon: 135.8069,
          why: "宇治是抹茶原乡，本店的生茶ゼリイ值得排队",
        },
        {
          time: "16:40",
          title: "MU515 · 关西空港 → 上海浦东",
          short: "关西空港",
          kind: "transit",
          detail: "",
          cost: "¥2,400",
          lat: 34.4342,
          lon: 135.244,
          why: "宇治 JR 直达关西空港约 100 分钟，赶傍晚航班回上海",
          ticket: {
            line: "东航",
            no: "MU515",
            from: "关西空港",
            to: "上海浦东",
            dep: "16:40",
            arr: "18:20",
            dur: "2h",
            seat: "经济舱",
            mode: "flight",
            via: "宇治 JR 直达关西空港约 100 分",
          },
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// 3) 稻城亚丁 · 蓝色星球四日（成都中转直飞，国内·高德底图）
// ─────────────────────────────────────────────────────────────────────────────
const YADING: DemoTrip = {
  slug: "yading",
  name: "稻城亚丁",
  en: "YADING",
  region: "中国 · 四川甘孜",
  tagline: "雪山、草原和高山湖",
  origin: "无锡",
  transport: "flight",
  transportNote: "成都中转 ✈ 稻城亚丁机场",
  dateLabel: "09.25 – 09.28",
  durationLabel: "亚丁秋色四日",
  partySize: 2,
  budgetLabel: "¥5,500 / 人",
  budgetValue: 11000,
  style: "高原雪山 · 徒步观湖 · 循序适应海拔，节奏张弛有度",
  itineraryTitle: "无锡 → 稻城亚丁 · 蓝色星球四日",
  overview:
    "无锡经成都中转，直飞海拔 4411 米的稻城亚丁机场——世界最高民用机场。第一天在稻城县城缓步适应海拔，第二天走短线冲古寺与珍珠海，第三天上长线牛奶海、五色海，第四天赏桑堆红草地后返程。全程按高原节奏编排，先低后高不逞强。",
  tiles: "amap",
  featured: true,
  highlights: ["世界最高民用机场", "珍珠海 + 冲古寺", "牛奶海 · 五色海长线", "桑堆红草地"],
  references: [
    { label: "去程", value: "3U 无锡硕放 → 稻城亚丁（成都天府中转）· 约¥2,600" },
    { label: "返程", value: "3U 稻城亚丁 → 无锡硕放（成都天府中转）· 约¥2,600" },
    { label: "景区门票", value: "亚丁景区门票 ¥146 + 观光车 ¥120，长线洛绒牛场电瓶车 ¥80 单程" },
    { label: "高原提醒", value: "机场海拔 4411m，落地慢走勿剧烈运动；首晚宿稻城县城 3750m 过渡" },
  ],
  days: [
    {
      day: 1,
      date: "09.25",
      dow: "周四",
      theme: "直上高原 · 稻城适应",
      tab: "落地稻城",
      summary: "今日约 ¥3,200 · 含机票与首晚",
      stops: [
        {
          time: "07:40",
          title: "3U · 无锡 → 稻城亚丁（成都中转）",
          short: "稻城亚丁机场",
          kind: "transit",
          detail: "",
          cost: "¥2,600",
          lat: 29.3231,
          lon: 100.0533,
          why: "成都天府中转直飞稻城，落地即海拔 4411m，全程放慢动作",
          ticket: {
            line: "川航",
            no: "3U",
            from: "无锡硕放",
            to: "稻城亚丁",
            dep: "07:40",
            arr: "14:30",
            dur: "约 7h",
            seat: "经济舱",
            mode: "flight",
            via: "成都天府中转",
          },
        },
        {
          time: "15:30",
          title: "尊胜塔林（稻城白塔）",
          short: "稻城白塔",
          kind: "activity",
          detail: "康巴地区最大塔林，缓步适应海拔",
          cost: null,
          lat: 29.045,
          lon: 100.296,
          why: "落地第一站不爬升，绕塔慢走让身体先适应高原",
        },
        {
          time: "16:30",
          title: "傍河 · 万亩青杨林",
          short: "青杨林",
          kind: "activity",
          detail: "金秋青杨与河谷落日，色彩浓烈",
          cost: null,
          lat: 29.06,
          lon: 100.3,
          why: "九月青杨转金，河谷落日是稻城的第一张明信片",
        },
        {
          time: "18:00",
          title: "稻城县城 · 亚丁红酒店",
          short: "稻城住宿",
          kind: "rest",
          detail: "海拔 3750m，弥散供氧客栈",
          cost: "¥420/晚",
          lat: 29.0378,
          lon: 100.2986,
          why: "先在县城住一晚过渡，比直接进景区更稳妥",
        },
        {
          time: "19:00",
          title: "藏家牦牛火锅",
          short: "牦牛火锅",
          kind: "food",
          detail: "牦牛肉配菌菇，暖身补能量",
          cost: "¥90",
          lat: 29.038,
          lon: 100.299,
          why: "高原易疲劳，热汤火锅补充热量、别贪杯",
        },
      ],
    },
    {
      day: 2,
      date: "09.26",
      dow: "周五",
      theme: "短线 · 冲古寺与珍珠海",
      tab: "冲古珍珠海",
      summary: "今日约 ¥1,050 · 含门票与住宿",
      stops: [
        {
          time: "08:00",
          title: "亚丁景区 · 换乘观光车",
          short: "亚丁景区",
          kind: "transit",
          detail: "门票 ¥146 + 观光车 ¥120，进香格里拉镇",
          cost: "¥266",
          lat: 28.9,
          lon: 100.33,
          why: "从稻城转场亚丁，观光车盘山进沟，省下体力给徒步",
        },
        {
          time: "09:30",
          title: "冲古寺",
          short: "冲古寺",
          kind: "activity",
          detail: "仙乃日雪山脚下的古寺草甸",
          cost: null,
          lat: 28.427,
          lon: 100.305,
          why: "短线起点，雪山下的草甸是热身也是取景地",
        },
        {
          time: "10:30",
          title: "珍珠海（卓玛拉措）",
          short: "珍珠海",
          kind: "activity",
          detail: "仙乃日倒影的碧绿圣湖，短线精华",
          cost: null,
          lat: 28.418,
          lon: 100.301,
          why: "短线最美一段，湖面倒映仙乃日，往返约 2 小时",
        },
        {
          time: "13:00",
          title: "亚丁村 · 藏面与酥油茶",
          short: "亚丁村午餐",
          kind: "food",
          detail: "村里简餐，藏面配酥油茶",
          cost: "¥50",
          lat: 28.434,
          lon: 100.332,
          why: "住景区内的亚丁村，午餐后就近休整养精蓄锐",
        },
        {
          time: "15:00",
          title: "亚丁村观景客栈",
          short: "亚丁村住宿",
          kind: "rest",
          detail: "住景区内，次日长线不折返",
          cost: "¥680/晚",
          lat: 28.4335,
          lon: 100.3325,
          why: "宿在村里，第三天一早直接上长线，省两小时车程",
        },
      ],
    },
    {
      day: 3,
      date: "09.27",
      dow: "周六",
      theme: "长线 · 牛奶海与五色海",
      tab: "牛奶海长线",
      summary: "今日约 ¥820 · 含电瓶车与住宿",
      stops: [
        {
          time: "06:30",
          title: "洛绒牛场",
          short: "洛绒牛场",
          kind: "activity",
          detail: "三神山环抱的高山牧场，长线起点",
          cost: "¥80",
          lat: 28.383,
          lon: 100.312,
          why: "电瓶车到牛场省 7 公里，把体力留给最后的爬升",
        },
        {
          time: "09:00",
          title: "牛奶海（俄绒措）",
          short: "牛奶海",
          kind: "activity",
          detail: "海拔 4600m 的翡翠圣湖，徒步终点",
          cost: null,
          lat: 28.365,
          lon: 100.323,
          why: "全程精华，最后一段陡坡慢走，湖水绿到不真实",
        },
        {
          time: "10:30",
          title: "五色海",
          short: "五色海",
          kind: "activity",
          detail: "央迈勇脚下，光线折出五种颜色",
          cost: null,
          lat: 28.363,
          lon: 100.326,
          why: "就在牛奶海上方 20 分钟，晴天光线一到湖变五色",
        },
        {
          time: "13:00",
          title: "洛绒牛场简餐",
          short: "牛场简餐",
          kind: "food",
          detail: "下撤后在牛场补给热食",
          cost: "¥60",
          lat: 28.3835,
          lon: 100.3115,
          why: "长线消耗大，返程先在牛场吃口热的再坐车",
        },
        {
          time: "17:00",
          title: "亚丁村观景客栈",
          short: "亚丁村住宿",
          kind: "rest",
          detail: "再宿一晚，好好休息",
          cost: "¥680/晚",
          lat: 28.4335,
          lon: 100.3325,
          why: "长线后早点回村休整，为返程养足精神",
        },
      ],
    },
    {
      day: 4,
      date: "09.28",
      dow: "周日",
      theme: "桑堆红草地 · 返程",
      tab: "红草地返程",
      summary: "今日约 ¥2,600 · 含返程机票",
      stops: [
        {
          time: "07:30",
          title: "桑堆红草地",
          short: "红草地",
          kind: "activity",
          detail: "九月限定的红色湿地，只此半月",
          cost: null,
          lat: 29.19,
          lon: 100.2,
          why: "返机场顺路，九月下旬水草转红，错过要等一年",
        },
        {
          time: "10:00",
          title: "稻城亚丁机场打卡",
          short: "机场打卡",
          kind: "activity",
          detail: "海拔 4411m，世界最高民用机场",
          cost: null,
          lat: 29.3231,
          lon: 100.0533,
          why: "候机前和「世界最高机场」标识合影，行程收尾",
        },
        {
          time: "12:40",
          title: "3U · 稻城亚丁 → 无锡（成都中转）",
          short: "返程",
          kind: "transit",
          detail: "",
          cost: "¥2,600",
          lat: 29.3231,
          lon: 100.0533,
          why: "午后航班经成都回无锡，当晚到家",
          ticket: {
            line: "川航",
            no: "3U",
            from: "稻城亚丁",
            to: "无锡硕放",
            dep: "12:40",
            arr: "20:10",
            dur: "约 7.5h",
            seat: "经济舱",
            mode: "flight",
            via: "成都天府中转",
          },
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// 4) 冰岛 · 冰与火五日（浦东经赫尔辛基转机，出境·OSM 底图）
// ─────────────────────────────────────────────────────────────────────────────
const ICELAND: DemoTrip = {
  slug: "iceland",
  name: "冰岛",
  en: "ICELAND",
  region: "北欧 · 冰岛",
  tagline: "看瀑布、冰川和极光",
  origin: "无锡",
  transport: "flight",
  transportNote: "浦东经赫尔辛基 ✈ 雷克雅未克",
  dateLabel: "09.10 – 09.14",
  durationLabel: "冰岛五日",
  partySize: 2,
  budgetLabel: "¥26,000 / 人",
  budgetValue: 52000,
  style: "自驾环岛南线 · 瀑布冰川黑沙滩 · 追极光，节奏自由",
  itineraryTitle: "无锡 → 冰岛 · 环岛五日",
  overview:
    "无锡到上海浦东，经赫尔辛基转机飞抵凯夫拉维克，取车自驾冰岛南线。黄金圈的裂谷、间歇泉与黄金瀑布，南岸的塞里雅兰与斯科加瀑布、雷尼斯黑沙滩，直到杰古沙龙冰河湖与钻石冰沙滩，末日在蓝湖泡汤后返程。九月是极光季的开端，夜里远离光害有机会遇见。",
  tiles: "osm",
  featured: true,
  highlights: ["黄金圈三重奏", "南岸瀑布黑沙滩", "杰古沙龙冰河湖", "蓝湖地热温泉"],
  references: [
    { label: "去程", value: "AY 上海浦东 → 凯夫拉维克（赫尔辛基转机）· 约¥7,800" },
    { label: "返程", value: "AY 凯夫拉维克 → 上海浦东（赫尔辛基转机）· 约¥7,800" },
    { label: "自驾", value: "凯夫拉维克机场取车，5 天约 800km，南线路况好；建议租 4×4" },
    { label: "极光提醒", value: "9 月中旬起有极光机会，查 vedur.is 极光预报，宿地远离城镇光害" },
  ],
  days: [
    {
      day: 1,
      date: "09.10",
      dow: "周三",
      theme: "抵达 · 雷克雅未克",
      tab: "落地雷市",
      summary: "今日约 ¥8,100 · 含机票与首晚",
      stops: [
        {
          time: "08:00",
          title: "AY · 上海浦东 → 凯夫拉维克",
          short: "凯夫拉维克",
          kind: "transit",
          detail: "",
          cost: "¥7,800",
          lat: 63.985,
          lon: -22.605,
          why: "赫尔辛基转机是浦东到冰岛的顺路航线，落地即取车",
          ticket: {
            line: "芬兰航空",
            no: "AY",
            from: "上海浦东",
            to: "凯夫拉维克",
            dep: "08:00",
            arr: "18:30",
            dur: "约 19h",
            seat: "经济舱",
            mode: "flight",
            via: "赫尔辛基转机",
          },
        },
        {
          time: "19:30",
          title: "雷克雅未克 · 市中心酒店",
          short: "雷市住宿",
          kind: "rest",
          detail: "老港区步行范围，落地先安顿",
          cost: "¥1,100/晚",
          lat: 64.1466,
          lon: -21.9426,
          why: "首晚不折腾，住在老港区吃顿好的、倒时差",
        },
        {
          time: "20:30",
          title: "Sægreifinn 龙虾汤（老港）",
          short: "龙虾汤",
          kind: "food",
          detail: "海边木屋的招牌龙虾汤，暖到心里",
          cost: "¥180",
          lat: 64.1516,
          lon: -21.9407,
          why: "冰岛物价高，这碗龙虾汤是公认高性价比的第一顿",
        },
      ],
    },
    {
      day: 2,
      date: "09.11",
      dow: "周四",
      theme: "黄金圈 · 裂谷间歇泉",
      tab: "黄金圈",
      summary: "今日约 ¥1,220 · 含午餐住宿",
      stops: [
        {
          time: "09:00",
          title: "辛格维利尔国家公园",
          short: "辛格维利尔",
          kind: "activity",
          detail: "欧亚与北美板块的裂谷，古议会遗址",
          cost: null,
          lat: 64.2559,
          lon: -21.1298,
          why: "站在两大板块之间的裂缝里，也是世界遗产",
        },
        {
          time: "11:30",
          title: "间歇泉 Geysir / Strokkur",
          short: "间歇泉",
          kind: "activity",
          detail: "Strokkur 每几分钟喷发一次",
          cost: null,
          lat: 64.3104,
          lon: -20.3024,
          why: "「Geyser」一词的词源地，等它喷发很治愈",
        },
        {
          time: "12:30",
          title: "Friðheimar 番茄温室餐厅",
          short: "番茄温室",
          kind: "food",
          detail: "地热温室里的无限量番茄汤",
          cost: "¥220",
          lat: 64.352,
          lon: -20.236,
          why: "在种满番茄的温室里喝番茄汤，冰岛限定的体验",
        },
        {
          time: "14:00",
          title: "黄金瀑布 Gullfoss",
          short: "黄金瀑布",
          kind: "activity",
          detail: "双层巨瀑跌入峡谷，黄金圈压轴",
          cost: null,
          lat: 64.3271,
          lon: -20.1199,
          why: "水量惊人的双层瀑布，晴天常挂彩虹",
        },
        {
          time: "18:00",
          title: "塞尔福斯 · 乡间旅馆",
          short: "塞尔福斯住宿",
          kind: "rest",
          detail: "南线中途小镇，明日直插南岸",
          cost: "¥1,000/晚",
          lat: 63.933,
          lon: -20.997,
          why: "住到南线上，缩短次日到瀑布群的车程",
        },
      ],
    },
    {
      day: 3,
      date: "09.12",
      dow: "周五",
      theme: "南岸瀑布 · 黑沙滩",
      tab: "南岸黑沙滩",
      summary: "今日约 ¥1,230 · 含午餐住宿",
      stops: [
        {
          time: "09:00",
          title: "塞里雅兰瀑布",
          short: "塞里雅兰",
          kind: "activity",
          detail: "可绕到瀑布水帘后方的名瀑",
          cost: null,
          lat: 63.6156,
          lon: -19.9884,
          why: "少见的能走到背后的瀑布，穿好防水衣",
        },
        {
          time: "10:30",
          title: "斯科加瀑布",
          short: "斯科加",
          kind: "activity",
          detail: "60 米宽的水幕，常见双彩虹",
          cost: null,
          lat: 63.532,
          lon: -19.5114,
          why: "可登顶俯瞰，晴天水雾里几乎必有彩虹",
        },
        {
          time: "13:00",
          title: "维克镇 Suður-Vík 餐厅",
          short: "维克午餐",
          kind: "food",
          detail: "南岸小镇的羊肉汤与海鲜",
          cost: "¥180",
          lat: 63.4186,
          lon: -19.006,
          why: "维克是南线唯一像样的补给点，午餐正合适",
        },
        {
          time: "14:30",
          title: "雷尼斯黑沙滩",
          short: "黑沙滩",
          kind: "activity",
          detail: "玄武岩柱与海蚀柱，注意疯狗浪",
          cost: null,
          lat: 63.4034,
          lon: -19.0448,
          why: "冰岛最著名的黑沙滩，务必远离海浪线保平安",
        },
        {
          time: "18:00",
          title: "维克镇酒店",
          short: "维克住宿",
          kind: "rest",
          detail: "海边小镇过夜，夜里守极光",
          cost: "¥1,050/晚",
          lat: 63.418,
          lon: -19.006,
          why: "维克光害小，天晴时门口就能看极光",
        },
      ],
    },
    {
      day: 4,
      date: "09.13",
      dow: "周六",
      theme: "冰河湖 · 钻石沙滩",
      tab: "杰古沙龙",
      summary: "今日约 ¥1,430 · 含冰川团住宿",
      stops: [
        {
          time: "08:00",
          title: "斯卡夫塔 · 瓦特纳冰川徒步",
          short: "冰川徒步",
          kind: "activity",
          detail: "向导带队踏上欧洲最大冰川",
          cost: "¥380",
          lat: 64.016,
          lon: -16.966,
          why: "必须跟向导团上冰，冰爪与镐具随团提供",
        },
        {
          time: "12:00",
          title: "杰古沙龙冰河湖",
          short: "冰河湖",
          kind: "activity",
          detail: "巨大浮冰漂向大海，可乘水陆船",
          cost: null,
          lat: 64.0784,
          lon: -16.2306,
          why: "整趟冰岛的高潮，蓝白浮冰安静漂过眼前",
        },
        {
          time: "13:30",
          title: "钻石冰沙滩",
          short: "钻石沙滩",
          kind: "activity",
          detail: "黑沙上散落晶莹的碎冰",
          cost: null,
          lat: 64.043,
          lon: -16.176,
          why: "就在冰河湖对面马路，黑沙上的冰块像钻石",
        },
        {
          time: "19:00",
          title: "克…克劳斯图尔 乡间住宿",
          short: "极光住宿",
          kind: "rest",
          detail: "远离光害，整晚守候极光",
          cost: "¥1,050/晚",
          lat: 63.79,
          lon: -18.06,
          why: "选在南线荒野过夜，极光概率比城镇高得多",
        },
      ],
    },
    {
      day: 5,
      date: "09.14",
      dow: "周日",
      theme: "蓝湖温泉 · 返程",
      tab: "蓝湖返程",
      summary: "今日约 ¥8,400 · 含蓝湖与机票",
      stops: [
        {
          time: "11:00",
          title: "蓝湖地热温泉",
          short: "蓝湖",
          kind: "activity",
          detail: "乳蓝色地热泻湖，登机前泡一场",
          cost: "¥600",
          lat: 63.88,
          lon: -22.449,
          why: "蓝湖就在机场附近，还车前泡汤是完美收尾（需预约）",
        },
        {
          time: "15:30",
          title: "AY · 凯夫拉维克 → 上海浦东",
          short: "凯夫拉维克",
          kind: "transit",
          detail: "",
          cost: "¥7,800",
          lat: 63.985,
          lon: -22.605,
          why: "蓝湖到机场 20 分钟，泡完汤从容还车登机",
          ticket: {
            line: "芬兰航空",
            no: "AY",
            from: "凯夫拉维克",
            to: "上海浦东",
            dep: "15:30",
            arr: "次日",
            dur: "约 19h",
            seat: "经济舱",
            mode: "flight",
            via: "赫尔辛基转机",
          },
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// 5) 圣托里尼 · 爱琴海四日（浦东经雅典转机，出境·OSM 底图）
// ─────────────────────────────────────────────────────────────────────────────
const SANTORINI: DemoTrip = {
  slug: "santorini",
  name: "圣托里尼",
  en: "SANTORINI",
  region: "希腊 · 基克拉泽斯",
  tagline: "蓝白小镇，看爱琴海日落",
  origin: "无锡",
  transport: "flight",
  transportNote: "浦东经雅典 ✈ 圣托里尼",
  dateLabel: "06.15 – 06.18",
  durationLabel: "爱琴海四日",
  partySize: 2,
  budgetLabel: "¥18,000 / 人",
  budgetValue: 36000,
  style: "海岛度假 · 蓝白小镇与日落 · 酒庄海鲜，节奏慵懒",
  itineraryTitle: "无锡 → 圣托里尼 · 爱琴海四日",
  overview:
    "无锡到上海浦东，经雅典转机飞抵圣托里尼。四天从费拉的火山口崖景，到伊亚全球闻名的日落，再到红沙滩、古锡拉遗址与 Santo Wines 酒庄，末日沿火山口崖顶徒步后返程。六月天气晴好、人潮未至峰值，正是爱琴海最舒服的时节。",
  tiles: "osm",
  highlights: ["费拉火山口崖景", "伊亚绝美日落", "红沙滩 + 古锡拉", "火山酒庄品酒"],
  references: [
    { label: "去程", value: "浦东 → 圣托里尼（雅典转机）· 约¥6,600" },
    { label: "返程", value: "圣托里尼 → 浦东（雅典转机）· 约¥6,600" },
    { label: "住宿", value: "费拉火山口崖景酒店 · 三晚约 ¥4,800 · 无边泳池朝落日" },
    { label: "小贴士", value: "伊亚日落需提早 1 小时占位；岛内租 ATV/包车最灵活，缆车常排长队" },
  ],
  days: [
    {
      day: 1,
      date: "06.15",
      dow: "周日",
      theme: "抵达 · 费拉崖景",
      tab: "落地费拉",
      summary: "今日约 ¥8,460 · 含机票与首晚",
      stops: [
        {
          time: "08:00",
          title: "浦东 → 圣托里尼（雅典转机）",
          short: "圣托里尼机场",
          kind: "transit",
          detail: "",
          cost: "¥6,600",
          lat: 36.399,
          lon: 25.479,
          why: "雅典转机是进圣岛的常规航线，落地即入住崖景酒店",
          ticket: {
            line: "国航/爱琴",
            no: "CA·A3",
            from: "上海浦东",
            to: "圣托里尼",
            dep: "08:00",
            arr: "次日",
            dur: "约 16h",
            seat: "经济舱",
            mode: "flight",
            via: "雅典转机",
          },
        },
        {
          time: "17:00",
          title: "费拉 · 火山口崖景酒店",
          short: "费拉住宿",
          kind: "rest",
          detail: "无边泳池正对火山口",
          cost: "¥1,600/晚",
          lat: 36.4166,
          lon: 25.4324,
          why: "住在费拉崖边，推门就是整片火山口海景",
        },
        {
          time: "18:30",
          title: "费拉老城漫步",
          short: "费拉老城",
          kind: "activity",
          detail: "蓝白巷弄与崖边观景台",
          cost: null,
          lat: 36.416,
          lon: 25.431,
          why: "落地先在费拉散步，熟悉岛上的蓝白节奏",
        },
        {
          time: "20:00",
          title: "Argo 崖边餐厅",
          short: "Argo 餐厅",
          kind: "food",
          detail: "番茄丸子与爱琴海鲜，看夜色海景",
          cost: "¥260",
          lat: 36.4172,
          lon: 25.4318,
          why: "崖边餐厅配落日余晖，第一晚就把海景吃满",
        },
      ],
    },
    {
      day: 2,
      date: "06.16",
      dow: "周一",
      theme: "伊亚 · 蓝顶与日落",
      tab: "伊亚日落",
      summary: "今日约 ¥300",
      stops: [
        {
          time: "10:00",
          title: "伊亚小镇 Oia",
          short: "伊亚",
          kind: "activity",
          detail: "蓝顶教堂与雪白迷巷，明信片本片",
          cost: null,
          lat: 36.4618,
          lon: 25.3753,
          why: "圣托里尼最上镜的小镇，白天人少时慢慢逛",
        },
        {
          time: "12:30",
          title: "阿莫迪湾 Amoudi Bay",
          short: "阿莫迪湾",
          kind: "food",
          detail: "崖下渔港的海鲜午餐",
          cost: "¥300",
          lat: 36.463,
          lon: 25.369,
          why: "从伊亚走三百级台阶下到渔港，吃最新鲜的海鲜",
        },
        {
          time: "15:00",
          title: "伊亚城堡遗址",
          short: "伊亚城堡",
          kind: "activity",
          detail: "看日落的最佳制高点",
          cost: null,
          lat: 36.461,
          lon: 25.3735,
          why: "傍晚人满为患，先来踩点选好机位",
        },
        {
          time: "19:00",
          title: "伊亚日落",
          short: "伊亚日落",
          kind: "activity",
          detail: "全球最负盛名的日落，提早占位",
          cost: null,
          lat: 36.4618,
          lon: 25.3753,
          why: "圣托里尼的招牌时刻，落日沉入爱琴海全场鼓掌",
        },
      ],
    },
    {
      day: 3,
      date: "06.17",
      dow: "周二",
      theme: "火山红滩 · 酒庄日落",
      tab: "红滩酒庄",
      summary: "今日约 ¥360",
      stops: [
        {
          time: "09:30",
          title: "红沙滩 Red Beach",
          short: "红沙滩",
          kind: "activity",
          detail: "火山红崖下的独特海滩",
          cost: null,
          lat: 36.348,
          lon: 25.395,
          why: "岛南的火山地貌，红色岩壁配爱琴海蓝",
        },
        {
          time: "11:00",
          title: "古代锡拉遗址",
          short: "古锡拉",
          kind: "activity",
          detail: "山顶的古希腊城邦遗迹",
          cost: "¥60",
          lat: 36.362,
          lon: 25.478,
          why: "登上梅萨山看两侧海湾，兼补一段古希腊史",
        },
        {
          time: "13:00",
          title: "佩里萨黑沙滩",
          short: "佩里萨",
          kind: "food",
          detail: "黑沙滩边的海鲜塔维纳",
          cost: "¥180",
          lat: 36.354,
          lon: 25.474,
          why: "午后在黑沙滩泡海、吃希腊沙拉，慵懒一下午",
        },
        {
          time: "17:00",
          title: "Santo Wines 酒庄",
          short: "Santo 酒庄",
          kind: "activity",
          detail: "火山土 Assyrtiko 白酒，边品边看日落",
          cost: "¥120",
          lat: 36.404,
          lon: 25.436,
          why: "露台品酒正对火山口日落，比伊亚更从容",
        },
      ],
    },
    {
      day: 4,
      date: "06.18",
      dow: "周三",
      theme: "崖顶徒步 · 返程",
      tab: "崖顶返程",
      summary: "今日约 ¥6,600 · 含返程机票",
      stops: [
        {
          time: "08:30",
          title: "费拉 → 伊默罗维格利 崖顶步道",
          short: "崖顶徒步",
          kind: "activity",
          detail: "沿火山口崖顶徒步至 Skaros 岩",
          cost: null,
          lat: 36.433,
          lon: 25.424,
          why: "清晨凉爽人少，一路都是火山口全景",
        },
        {
          time: "12:00",
          title: "圣托里尼 → 浦东（雅典转机）",
          short: "圣托里尼机场",
          kind: "transit",
          detail: "",
          cost: "¥6,600",
          lat: 36.399,
          lon: 25.479,
          why: "午后航班经雅典回上海，带一身海风与日落回家",
          ticket: {
            line: "爱琴/国航",
            no: "A3·CA",
            from: "圣托里尼",
            to: "上海浦东",
            dep: "12:00",
            arr: "次日",
            dur: "约 16h",
            seat: "经济舱",
            mode: "flight",
            via: "雅典转机",
          },
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// 6) 摩洛哥 · 撒哈拉五日（浦东经多哈转机，出境·OSM 底图）
// ─────────────────────────────────────────────────────────────────────────────
const MOROCCO: DemoTrip = {
  slug: "morocco",
  name: "摩洛哥",
  en: "MOROCCO",
  region: "北非 · 摩洛哥",
  tagline: "逛老城，去撒哈拉沙漠",
  origin: "无锡",
  transport: "flight",
  transportNote: "浦东经多哈 ✈ 马拉喀什",
  dateLabel: "10.10 – 10.14",
  durationLabel: "撒哈拉五日",
  partySize: 2,
  budgetLabel: "¥16,000 / 人",
  budgetValue: 32000,
  style: "沙漠公路旅行 · 古城麦地那与柏柏尔营地 · 塔吉锅薄荷茶",
  itineraryTitle: "无锡 → 摩洛哥 · 撒哈拉五日",
  overview:
    "无锡到上海浦东，经多哈转机飞抵马拉喀什，一路向东南穿越阿特拉斯山：世遗古城艾本哈杜、梅祖卡的撒哈拉沙丘骑骆驼看日落、柏柏尔营地星空，再北上千年古都菲斯的麦地那与皮革染坊。五天一条摩洛哥经典环线，暖色调拉满。",
  tiles: "osm",
  highlights: ["德吉玛广场夜市", "艾本哈杜世遗古城", "撒哈拉骑骆驼看日落", "菲斯古城皮革染坊"],
  references: [
    { label: "去程", value: "QR 上海浦东 → 马拉喀什（多哈转机）· 约¥5,200" },
    { label: "返程", value: "QR 菲斯 → 上海浦东（卡萨/多哈转机）· 约¥5,200" },
    { label: "行程方式", value: "全程建议包 4×4 向导车，5 天约 1,200km；沙漠段含骆驼与营地" },
    { label: "小贴士", value: "麦地那易迷路可请向导；撒哈拉昼夜温差大带件外套；随身备零钱付小费" },
  ],
  days: [
    {
      day: 1,
      date: "10.10",
      dow: "周五",
      theme: "抵达 · 马拉喀什夜市",
      tab: "落地红城",
      summary: "今日约 ¥5,800 · 含机票与首晚",
      stops: [
        {
          time: "08:00",
          title: "QR · 上海浦东 → 马拉喀什",
          short: "马拉喀什",
          kind: "transit",
          detail: "",
          cost: "¥5,200",
          lat: 31.6069,
          lon: -8.0363,
          why: "多哈转机是浦东到马拉喀什的顺畅航线，落地入住老城 Riad",
          ticket: {
            line: "卡塔尔航空",
            no: "QR",
            from: "上海浦东",
            to: "马拉喀什",
            dep: "08:00",
            arr: "次日",
            dur: "约 18h",
            seat: "经济舱",
            mode: "flight",
            via: "多哈转机",
          },
        },
        {
          time: "18:00",
          title: "老城 Riad 庭院旅馆",
          short: "马城住宿",
          kind: "rest",
          detail: "麦地那里的传统摩式庭院旅馆",
          cost: "¥520/晚",
          lat: 31.6295,
          lon: -7.986,
          why: "住进老城才有摩洛哥味，出门就是德吉玛广场",
        },
        {
          time: "19:30",
          title: "德吉玛广场夜市",
          short: "德吉玛广场",
          kind: "activity",
          detail: "耍蛇卖艺、现榨橙汁的露天大集",
          cost: null,
          lat: 31.6258,
          lon: -7.9891,
          why: "全非洲最热闹的广场，入夜变身巨大的美食与杂耍场",
        },
        {
          time: "20:30",
          title: "广场排档 · 塔吉锅",
          short: "塔吉锅",
          kind: "food",
          detail: "炭火塔吉与烤串，就着夜市烟火",
          cost: "¥90",
          lat: 31.626,
          lon: -7.9885,
          why: "第一晚就在夜市大排档吃塔吉锅，最地道的开场",
        },
      ],
    },
    {
      day: 2,
      date: "10.11",
      dow: "周六",
      theme: "花园宫殿 · 翻越阿特拉斯",
      tab: "马城翻山",
      summary: "今日约 ¥730 · 含午餐住宿",
      stops: [
        {
          time: "09:00",
          title: "马若雷勒花园",
          short: "马若雷勒",
          kind: "activity",
          detail: "YSL 钟爱的马约雷蓝花园",
          cost: "¥80",
          lat: 31.6417,
          lon: -8.0033,
          why: "一抹强烈的钴蓝配仙人掌，摩洛哥最出片的花园",
        },
        {
          time: "11:00",
          title: "巴希亚宫",
          short: "巴希亚宫",
          kind: "activity",
          detail: "摩洛哥雕饰工艺的巅峰宫殿",
          cost: "¥40",
          lat: 31.6216,
          lon: -7.9836,
          why: "满室的石膏雕花与彩绘木顶，看工匠的极致",
        },
        {
          time: "12:30",
          title: "库图比亚清真寺",
          short: "库图比亚",
          kind: "activity",
          detail: "马拉喀什地标宣礼塔",
          cost: null,
          lat: 31.6236,
          lon: -7.9934,
          why: "老城天际线的锚点，午后出发前顺路一览",
        },
        {
          time: "13:30",
          title: "Nomad 老城露台餐厅",
          short: "Nomad 午餐",
          kind: "food",
          detail: "麦地那屋顶露台的摩式改良菜",
          cost: "¥130",
          lat: 31.6289,
          lon: -7.9878,
          why: "俯瞰香料市场吃午餐，翻山前补足能量",
        },
        {
          time: "15:00",
          title: "Tizi n'Tichka 阿特拉斯山口",
          short: "阿特拉斯山口",
          kind: "activity",
          detail: "2260m 盘山公路穿越高阿特拉斯",
          cost: null,
          lat: 31.29,
          lon: -7.37,
          why: "翻越北非最高山脉的公路，一路是壮阔的干河谷",
        },
        {
          time: "18:30",
          title: "瓦尔扎扎特 酒店",
          short: "瓦城住宿",
          kind: "rest",
          detail: "「非洲好莱坞」影城小镇过夜",
          cost: "¥480/晚",
          lat: 30.92,
          lon: -6.91,
          why: "住到山那头，明早近距离拜访艾本哈杜",
        },
      ],
    },
    {
      day: 3,
      date: "10.12",
      dow: "周日",
      theme: "世遗古城 · 撒哈拉日落",
      tab: "撒哈拉",
      summary: "今日约 ¥890 · 含骆驼与营地",
      stops: [
        {
          time: "08:30",
          title: "艾本哈杜古城",
          short: "艾本哈杜",
          kind: "activity",
          detail: "千年夯土城，无数电影取景地",
          cost: "¥30",
          lat: 31.047,
          lon: -7.1318,
          why: "《角斗士》《权游》取景的世遗土城，晨光下最上镜",
        },
        {
          time: "10:00",
          title: "瓦尔扎扎特影城 · 玫瑰谷",
          short: "玫瑰谷",
          kind: "activity",
          detail: "途经绿洲峡谷与玫瑰产区",
          cost: null,
          lat: 30.92,
          lon: -6.91,
          why: "东行路上的绿洲风光，打破荒漠的单调",
        },
        {
          time: "16:00",
          title: "梅祖卡 · 撒哈拉沙丘",
          short: "梅祖卡",
          kind: "activity",
          detail: "抵达 Erg Chebbi 金色大沙丘边缘",
          cost: null,
          lat: 31.0997,
          lon: -4.0122,
          why: "一路荒原尽头，眼前突然升起橙红色的巨大沙丘",
        },
        {
          time: "17:00",
          title: "骑骆驼进沙漠看日落",
          short: "骆驼日落",
          kind: "activity",
          detail: "驼队翻越沙丘，登高看撒哈拉落日",
          cost: "¥260",
          lat: 31.11,
          lon: -3.98,
          why: "整趟旅程的高潮，驼铃声里看太阳沉进沙海",
        },
        {
          time: "19:30",
          title: "柏柏尔沙漠营地",
          short: "沙漠营地",
          kind: "rest",
          detail: "帐篷营地围炉鼓乐，头顶银河",
          cost: "¥600/晚",
          lat: 31.12,
          lon: -3.97,
          why: "睡在沙丘间的营地，夜里没有光害只有满天星",
        },
      ],
    },
    {
      day: 4,
      date: "10.13",
      dow: "周一",
      theme: "沙漠日出 · 长驱菲斯",
      tab: "沙漠赴菲斯",
      summary: "今日约 ¥660 · 含住宿晚餐",
      stops: [
        {
          time: "06:00",
          title: "撒哈拉沙丘日出",
          short: "沙丘日出",
          kind: "activity",
          detail: "沙脊上等第一缕阳光染红沙海",
          cost: null,
          lat: 31.11,
          lon: -3.98,
          why: "早起爬上沙丘，日出的撒哈拉值得赖床的代价",
        },
        {
          time: "10:00",
          title: "伊夫兰 · 中阿特拉斯雪松林",
          short: "伊夫兰",
          kind: "activity",
          detail: "「摩洛哥小瑞士」与巴巴利猕猴",
          cost: null,
          lat: 33.53,
          lon: -5.11,
          why: "长途北上途中的清凉山城，林中常有野生猕猴",
        },
        {
          time: "18:00",
          title: "菲斯 · 麦地那 Riad",
          short: "菲斯住宿",
          kind: "rest",
          detail: "千年古都老城里的庭院旅馆",
          cost: "¥520/晚",
          lat: 34.0653,
          lon: -4.977,
          why: "住进菲斯老城，明早深入世上最大的中世纪麦地那",
        },
        {
          time: "20:00",
          title: "老城摩式盛宴",
          short: "菲斯晚餐",
          kind: "food",
          detail: "手撕鸽肉派 pastilla 与库斯库斯",
          cost: "¥140",
          lat: 34.064,
          lon: -4.979,
          why: "菲斯是摩洛哥美食之都，pastilla 咸甜交织值得一试",
        },
      ],
    },
    {
      day: 5,
      date: "10.14",
      dow: "周二",
      theme: "菲斯古城 · 返程",
      tab: "菲斯返程",
      summary: "今日约 ¥5,280 · 含返程机票",
      stops: [
        {
          time: "08:30",
          title: "菲斯老城 · 蓝门",
          short: "菲斯蓝门",
          kind: "activity",
          detail: "Bab Bou Jeloud 蓝门与迷宫麦地那",
          cost: null,
          lat: 34.0625,
          lon: -4.9838,
          why: "九千条巷子的中世纪迷宫，从蓝门一头扎进去",
        },
        {
          time: "09:30",
          title: "Chouara 皮革染坊",
          short: "皮革染坊",
          kind: "activity",
          detail: "千年古法的露天彩色染缸",
          cost: "¥20",
          lat: 34.0666,
          lon: -4.9723,
          why: "从露台俯瞰蜂窝状染缸，菲斯最震撼的画面",
        },
        {
          time: "11:00",
          title: "老城薄荷茶与糕点",
          short: "薄荷茶",
          kind: "food",
          detail: "一壶摩洛哥薄荷茶配甜点收尾",
          cost: "¥60",
          lat: 34.065,
          lon: -4.977,
          why: "临行前喝壶「柏柏尔威士忌」薄荷茶，最摩洛哥的告别",
        },
        {
          time: "14:30",
          title: "QR · 菲斯 → 上海浦东",
          short: "菲斯机场",
          kind: "transit",
          detail: "",
          cost: "¥5,200",
          lat: 33.9273,
          lon: -4.9779,
          why: "菲斯机场经卡萨/多哈转机回上海，带一身沙漠暖色回家",
          ticket: {
            line: "卡塔尔航空",
            no: "QR",
            from: "菲斯",
            to: "上海浦东",
            dep: "14:30",
            arr: "次日",
            dur: "约 18h",
            seat: "经济舱",
            mode: "flight",
            via: "卡萨布兰卡 / 多哈转机",
          },
        },
      ],
    },
  ],
};

/** 六个 demo（首页灯箱顺序）。suzhou 与 iceland 标 featured 盖「AI 精选」印章。 */
export const DEMOS: Record<string, DemoTrip> = {
  suzhou: SUZHOU,
  kyoto: KYOTO,
  yading: YADING,
  iceland: ICELAND,
  santorini: SANTORINI,
  morocco: MOROCCO,
};

/** 首页灯箱与 /demo 路由遍历用的有序列表 */
export const DEMO_LIST: DemoTrip[] = [
  SUZHOU,
  KYOTO,
  YADING,
  ICELAND,
  SANTORINI,
  MOROCCO,
];

export function getDemo(slug: string): DemoTrip | undefined {
  return DEMOS[slug];
}

/**
 * 首页展示带（ShowcaseTrip 默认）与两套地图组件的向后兼容别名 —— 保持首页
 * 「无锡 → 苏州」实景演示零改动。
 */
export const DAYS: ShowDay[] = SUZHOU.days;

/**
 * 首页 Hero 专属定制示例：「苏州古城 · 一日漫步」步行环线。
 * 六站从北面园林群（拙政园/苏博/狮子林）一路向南穿平江路、观前街到网师园夜花园，
 * 坐标真实 WGS-84、贴合古城步行动线——专为 Hero 右侧真地图上的路径而设计。
 * 独立于六个 demo（不进灯箱），仅供 Hero 的 HeroMock + HeroTripMap 使用。
 */
export const HERO_DAY: ShowDay = {
  day: 1,
  date: "07.11",
  dow: "周六",
  theme: "苏州古城 · 一日游",
  tab: "古城一日",
  summary: "六个景点 · 全程步行",
  stops: [
    {
      time: "09:00",
      title: "拙政园",
      short: "拙政园",
      kind: "activity",
      detail: "中国四大名园之首，清晨人少光线最好",
      cost: "¥80",
      lat: 31.3236,
      lon: 120.629,
    },
    {
      time: "10:30",
      title: "苏州博物馆",
      short: "苏州博物馆",
      kind: "activity",
      detail: "贝聿铭封山之作，与拙政园一墙之隔",
      cost: "免费预约",
      lat: 31.3228,
      lon: 120.6262,
    },
    {
      time: "11:30",
      title: "狮子林",
      short: "狮子林",
      kind: "activity",
      detail: "太湖石堆成的假山，走起来像迷宫",
      cost: "¥40",
      lat: 31.3234,
      lon: 120.6306,
    },
    {
      time: "14:00",
      title: "平江路历史街区",
      short: "平江路",
      kind: "activity",
      detail: "宋代格局的老街，沿河都是老房子",
      cost: null,
      lat: 31.3175,
      lon: 120.6335,
    },
    {
      time: "16:00",
      title: "观前街 · 采芝斋",
      short: "观前街",
      kind: "food",
      detail: "百年苏式糖果铺，捎份松子糖伴手礼",
      cost: "¥80",
      lat: 31.3127,
      lon: 120.624,
    },
    {
      time: "19:30",
      title: "网师园 · 夜花园",
      short: "网师园",
      kind: "activity",
      detail: "晚上在园林里看一场昆曲",
      cost: "¥100",
      lat: 31.302,
      lon: 120.6321,
    },
  ],
};

/** 显示用花费字符串 → 数字（存库/预算用）。"¥688/晚"→688，"免费预约"→0，null→0 */
export function costToNumber(cost: string | null | undefined): number {
  if (!cost) return 0;
  const m = cost.replace(/,/g, "").match(/-?\d+(\.\d+)?/);
  return m ? Number(m[0]) : 0;
}

/** 两点球面距离（km），用于「今日动线」统计（真实 WGS-84） */
export function haversineKm(a: Stop, b: Stop): number {
  const R = 6371;
  const rad = (x: number) => (x * Math.PI) / 180;
  const dLat = rad(b.lat - a.lat);
  const dLon = rad(b.lon - a.lon);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
